//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DTO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THANHTRIEUMIKE;Initial Catalog=ql_quanao;Integrated Security=True;Tru" +
            "st Server Certificate=True;User ID=sa;Password=123;")]
        public string ql_quanaoConnectionString {
            get {
                return ((string)(this["ql_quanaoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THANHTRIEUMIKE;Initial Catalog=ql_quanao;Integrated Security=True;Tru" +
            "st Server Certificate=True;User ID=sa;Password=123;")]
        public string ql_quanaoConnectionString1 {
            get {
                return ((string)(this["ql_quanaoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THANHTRIEUMIKE;Initial Catalog=ql_quanao;Integrated Security=True;Tru" +
            "st Server Certificate=True;User ID=sa;Password=123;")]
        public string ql_quanaoConnectionString2 {
            get {
                return ((string)(this["ql_quanaoConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=THANHTRIEUMIKE;Initial Catalog=ql_quanao;Integrated Security=True;Enc" +
            "rypt=True;TrustServerCertificate=True")]
        public string ql_quanaoConnectionString3 {
            get {
                return ((string)(this["ql_quanaoConnectionString3"]));
            }
        }
    }
}
